// File generated manually from Firebase project config.
// DO NOT edit this file manually — replace via flutterfire configure.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  // ── Web ──────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAngLALLuq_d2nkTdh13yNsYoKDpat0X8U',
    authDomain: 'hakbanghero.firebaseapp.com',
    projectId: 'hakbanghero',
    storageBucket: 'hakbanghero.firebasestorage.app',
    messagingSenderId: '467538787680',
    appId: '1:467538787680:web:a259d6319fbae7c6b9f205',
    measurementId: 'G-ME4HJSY1ZR',
  );

  // ── Android (same project, add SHA later for Google Sign-In) ─────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAngLALLuq_d2nkTdh13yNsYoKDpat0X8U',
    authDomain: 'hakbanghero.firebaseapp.com',
    projectId: 'hakbanghero',
    storageBucket: 'hakbanghero.firebasestorage.app',
    messagingSenderId: '467538787680',
    appId: '1:467538787680:web:a259d6319fbae7c6b9f205',
  );

  // ── iOS ──────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAngLALLuq_d2nkTdh13yNsYoKDpat0X8U',
    authDomain: 'hakbanghero.firebaseapp.com',
    projectId: 'hakbanghero',
    storageBucket: 'hakbanghero.firebasestorage.app',
    messagingSenderId: '467538787680',
    appId: '1:467538787680:web:a259d6319fbae7c6b9f205',
  );
}